# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditWindow(object):
    def setupUi(self, EditWindow):
        EditWindow.setObjectName("EditWindow")
        EditWindow.resize(480, 265)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditWindow.sizePolicy().hasHeightForWidth())
        EditWindow.setSizePolicy(sizePolicy)
        EditWindow.setMinimumSize(QtCore.QSize(480, 235))
        EditWindow.setMaximumSize(QtCore.QSize(480, 265))
        self.centralwidget = QtWidgets.QWidget(EditWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelNameEdit = QtWidgets.QLabel(self.centralwidget)
        self.labelNameEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.labelNameEdit.setObjectName("labelNameEdit")
        self.verticalLayout.addWidget(self.labelNameEdit)
        self.labelTypeEdit = QtWidgets.QLabel(self.centralwidget)
        self.labelTypeEdit.setObjectName("labelTypeEdit")
        self.verticalLayout.addWidget(self.labelTypeEdit)
        self.labelNumberEdit = QtWidgets.QLabel(self.centralwidget)
        self.labelNumberEdit.setObjectName("labelNumberEdit")
        self.verticalLayout.addWidget(self.labelNumberEdit)
        self.labelPlaceEdit = QtWidgets.QLabel(self.centralwidget)
        self.labelPlaceEdit.setObjectName("labelPlaceEdit")
        self.verticalLayout.addWidget(self.labelPlaceEdit)
        self.labelYearEdit = QtWidgets.QLabel(self.centralwidget)
        self.labelYearEdit.setObjectName("labelYearEdit")
        self.verticalLayout.addWidget(self.labelYearEdit)
        self.labelDatePovEdit = QtWidgets.QLabel(self.centralwidget)
        self.labelDatePovEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.labelDatePovEdit.setObjectName("labelDatePovEdit")
        self.verticalLayout.addWidget(self.labelDatePovEdit)
        self.labelDateNextPovEdit = QtWidgets.QLabel(self.centralwidget)
        self.labelDateNextPovEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.labelDateNextPovEdit.setObjectName("labelDateNextPovEdit")
        self.verticalLayout.addWidget(self.labelDateNextPovEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNameEdit.setTabletTracking(False)
        self.lineEditNameEdit.setObjectName("lineEditNameEdit")
        self.verticalLayout_2.addWidget(self.lineEditNameEdit)
        self.comboBoxTypeEdit = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxTypeEdit.setObjectName("comboBoxTypeEdit")
        self.verticalLayout_2.addWidget(self.comboBoxTypeEdit)
        self.lineEditNumberEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNumberEdit.setObjectName("lineEditNumberEdit")
        self.verticalLayout_2.addWidget(self.lineEditNumberEdit)
        self.comboBoxPlaceEdit = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxPlaceEdit.setObjectName("comboBoxPlaceEdit")
        self.verticalLayout_2.addWidget(self.comboBoxPlaceEdit)
        self.dateEditYearEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditYearEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateEditYearEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateEditYearEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateEditYearEdit.setObjectName("dateEditYearEdit")
        self.verticalLayout_2.addWidget(self.dateEditYearEdit)
        self.dateEditPovEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditPovEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateEditPovEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditPovEdit.setObjectName("dateEditPovEdit")
        self.verticalLayout_2.addWidget(self.dateEditPovEdit)
        self.dateEditNextPovEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditNextPovEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateEditNextPovEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditNextPovEdit.setObjectName("dateEditNextPovEdit")
        self.verticalLayout_2.addWidget(self.dateEditNextPovEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setObjectName("btnEdit")
        self.gridLayout.addWidget(self.btnEdit, 1, 0, 1, 2)
        EditWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EditWindow)
        QtCore.QMetaObject.connectSlotsByName(EditWindow)

    def retranslateUi(self, EditWindow):
        _translate = QtCore.QCoreApplication.translate
        EditWindow.setWindowTitle(_translate("EditWindow", "Изменить прибор"))
        self.labelNameEdit.setText(_translate("EditWindow", "Название прибора:"))
        self.labelTypeEdit.setText(_translate("EditWindow", "Тип прибора:"))
        self.labelNumberEdit.setText(_translate("EditWindow", "Заводской номер:"))
        self.labelPlaceEdit.setText(_translate("EditWindow", "Место установки:"))
        self.labelYearEdit.setText(_translate("EditWindow", "Год выпуска:"))
        self.labelDatePovEdit.setText(_translate("EditWindow", "Дата поверки:"))
        self.labelDateNextPovEdit.setText(_translate("EditWindow", "Дата следующей поверки:"))
        self.dateEditYearEdit.setDisplayFormat(_translate("EditWindow", "yyyy"))
        self.btnEdit.setText(_translate("EditWindow", "Изменить"))


